# Generated by Django 5.2.1 on 2025-05-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_admin', '0002_rename_signupform_signup_alter_signup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='role',
            field=models.CharField(choices=[('0', 'Teacher'), ('1', 'Admin')]),
        ),
    ]
