# Generated by Django 5.2.1 on 2025-05-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_admin', '0004_admin_comment_task_teacher_delete_signup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assighned_to',
            new_name='assigned_to',
        ),
    ]
