# Generated by Django 5.2.1 on 2025-06-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_admin', '0006_remove_comment_id_comment_admin_comment_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='perioty',
            new_name='priority',
        ),
    ]
