# Generated by Django 5.2.1 on 2025-05-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUpForm',
            new_name='SignUp',
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['full_name'], 'verbose_name': 'Sign Up Form'},
        ),
    ]
